/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Hoja_de_Calificaci_nTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Hoja_de_Calificaci_nTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Hoja_de_Calificaci_n__c());
    }
}